apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tzgj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0016-tenant/tkrw-pr712-0075-0016-app/devfile-sample-tzgj@sha256:5aaf28f61094a16a58a480df83bd53a227165345d0e57c906347f67a3d6fc68e
        name: my-nodejs
        resources: {}
status: {}
